import type { Metadata } from "next";
import { SiteShell } from "@/components/site-shell";
import { PageHero, QuoteCta } from "@/components/page-parts";
import { publicAsset } from "@/lib/site-path";

export const metadata: Metadata = { title: "Apps", description: "WordPress, Shopify, React SaaS and API integration development from Emerald Pathways." };

const services = [
  { image: "apps_wordpress-v2.png", title: "WordPress App Development", copy: ["We design and build custom WordPress plugins and integrations tailored to extend your website’s core functionality while maintaining performance and scalability. Whether it's a bespoke booking system, custom API connector, membership gateway, or advanced short code-based functionality, our apps are built to comply with WordPress coding standards and are Gutenberg-compatible.", "We ensure clean PHP architecture, database efficiency, and seamless updates across the plugin lifecycle, delivering robust solutions that integrate effortlessly with your theme and third-party tools."] },
  { image: "apps_shopify-v2.png", title: "Shopify App Development", copy: ["Our Shopify app development services focus on crafting public, private, or custom apps that enhance merchant workflows and customer experience. Built using the Shopify API, Polaris design system, and React front-ends, we create embedded apps that support order management, custom product builders, subscription logic, and more.", "We ensure Shopify Partner compliance, OAuth 2.0 authentication, and Shopify CLI deployment for rapid iteration. Whether you're automating fulfilment or adding loyalty functionality, our apps are designed for performance, extensibility, and merchant-first usability."] },
  { image: "apps_react_saas-v2.png", title: "React-Based SaaS Applications", copy: ["We architect and develop full-stack SaaS platforms using the React framework alongside Next.js, Firebase, Supabase, or custom Node.js backends. With a focus on modular codebases, JWT-based auth flows, dynamic routing, and scalable state management via Redux or Zustand, our apps deliver fast-loading, secure, and user-friendly experiences.", "Each SaaS build includes responsive dashboards, granular access control, subscription handling via Stripe, and data visualisation with Chart.js or Recharts — ideal for businesses looking to productise internal tools or launch customer-facing platforms."] },
  { image: "apps_api_integrations-v2.png", title: "API Integrations", copy: ["We specialise in creating stable, secure, and scalable API integrations that connect your platforms to third-party services such as Stripe, Google Workspace, Pipedrive, SendGrid, and more. Whether RESTful or GraphQL, our integration work includes token-based authentication, webhook handling, rate-limit protection, and logging via services like LogRocket or Sentry.", "From middleware development to Zapier-style automation, we enable seamless data exchange and business logic across your digital ecosystem with minimal latency and maximum reliability."] },
];

export default function AppsPage() { return <SiteShell><main id="main-content" className="apps-page">
  <PageHero title="Apps" tagline="Empowering Your Digital Presence" tone="tone-forest" />
  <div className="content-shell"><section className="intro-copy"><p>Specialising in WordPress and Shopify app development, React-based SaaS solutions, and seamless integrations to elevate your business. Emerald Pathways is dedicated to connecting Irish businesses to the global market through innovative digital solutions. With expertise in web design, social media management, and project management, we craft tailored strategies to meet your unique needs.</p></section><QuoteCta />
  <h2 className="section-title">Our Services</h2><div className="service-list">{services.map(service => <article className="app-service" key={service.title}><div className="app-image"><img src={publicAsset(`assets/${service.image}`)} alt={service.title} width={1254} height={1254} loading="lazy" /></div><div className="app-copy"><h3>{service.title}</h3>{service.copy.map(p => <p key={p}>{p}</p>)}</div></article>)}</div></div>
</main></SiteShell>; }
