import type { Metadata } from "next";
import { SiteShell } from "@/components/site-shell";
import { PageHero, QuoteCta } from "@/components/page-parts";
import { publicAsset } from "@/lib/site-path";

export const metadata: Metadata = { title: "Web Design", description: "Responsive web design, ecommerce, training and ongoing website support from Emerald Pathways." };

const projects = [
  { image: "web_the_collective.png", name: "The Collective", kind: "eCommerce redesign", items: ["Upgrading of existing Shopify website platform with new theme", "Installation of automation software to handle ordering, vendor payouts and fulfilments.", "Social Media template design and brand guide.", "Product photography for content and online store.", "SEO research and implementation."] },
  { image: "web_tuath_glass.jpg", name: "Túath Glass", kind: "Website redesign project - ongoing", items: ["Installation of an Ecommerce platform to provide a safe and secure way for customers to purchase products online.", "Installation of a separate trade portal site and secure trade ordering portal.", "Product photography for both content and online store.", "SEO research and implementation.", "Remote online training provided to the client."] },
  { image: "web_universal_healing_tao.jpg", name: "Universal Healing Tao Ireland", kind: "Website design project", items: ["Business consultation and complete website design.", "Creation of video, photo and graphic design templates for the client.", "Training in blog creation and best SEO practices.", "2 years support including maintenance and security of the site."] },
  { image: "web_dublin_whiskey_tours.jpg", name: "Dublin Whiskey Tours", kind: "Website design project", items: ["Website redesign and upgrading of hosting package and site security.", "Installation of tour booking software and backend.", "Training provided to client in blog creation and SEO configuration to rank high for tourism keywords."] },
  { image: "web_picadice.png", name: "Picadice", kind: "Website redesign project", items: ["Website audit with recommendations.", "Installation of Instagram and Facebook shopping.", "Product photography for both content and online store.", "Social Media content creation for 6 months.", "SEO Audit with client implementation."] },
  { image: "web_irish_whiskey_magazine.png", name: "Irish Whiskey Magazine", kind: "Website redesign project ongoing", items: ["Upgrading of hosting packages and site security.", "SEO audit and problems resolved to rank higher in chosen category.", "Installation of an Ecommerce platform to provide a safe and secure way for customers to subscribe to and purchase products online.", "Ongoing email newsletter campaigns for two years.", "Social Media content creation for 2 years."] },
  { image: "web_design_whiskey_experts.jpg", name: "The Whiskey Experts", kind: "Website design project", items: ["Website redesign and upgrading of hosting package and site security.", "Installation of tour booking software.", "Training provided to clients in blog creation and SEO configuration to rank high for event keywords."] },
];

export default function WebDesignPage() { return <SiteShell><main id="main-content">
  <PageHero title="web design" tagline="We connect you to the world" tone="tone-sage" />
  <div className="content-shell"><section className="intro-copy"><p>Your online presence will probably be your customers first impression of your business. Your website needs to be fast to load, user friendly and make your customer want to return again and again.</p><p>In 2021 most potential customers will access your mobile website first and <a href="https://www.thinkwithgoogle.com/intl/en-ca/marketing-strategies/app-and-mobile/mobile-page-speed-new-industry-benchmarks/" target="_blank" rel="noreferrer">Google</a> says that 53% of mobile sites are abandoned if the website takes longer than three seconds to load. Having a slow website means losing half of your future customers before they have even experienced your brand. The next most important aspect is usability, can the customer navigate the site easily, can they purchase your products and share on social media with ease.</p><p>Our process involves assessing your existing website and providing a clear pathway to enhance your online presence. With our expertise and your vision, we will work to make your company stand out amongst the competition. When the initial project is completed we can monitor your website or offer full training on how to monitor, update and get the best from your new website.</p></section><QuoteCta />
  <div className="portfolio-list">{projects.map(project => <article className="portfolio-row" key={project.name}><img src={publicAsset(`assets/${project.image}`)} alt={`${project.name} website project`} /><div className="project-copy"><h3><span>{project.name}</span> - {project.kind}</h3><ul>{project.items.map(item => <li key={item}>{item}</li>)}</ul></div></article>)}</div></div>
</main></SiteShell>; }
