import type { Metadata } from "next";
import { SiteShell } from "@/components/site-shell";
import { PageHero, QuoteCta } from "@/components/page-parts";
import { publicAsset } from "@/lib/site-path";

export const metadata: Metadata = { title: "Social Media", description: "Social media content, photography, video, audits and brand design by Emerald Pathways." };

function GalleryHeading({ title, children }: { title: string; children: React.ReactNode }) { return <><h2 className="section-title">{title}</h2><p className="section-subtitle">{children}</p></>; }

export default function SocialMediaPage() { return <SiteShell><main id="main-content" className="social-page">
  <PageHero title="social media" tagline="engage with your customers the right way" tone="tone-sage" />
  <div className="content-shell"><section className="intro-copy"><p>Social media is often the first place people engage with your business, so it is important to present a strong brand image that immediately impacts potential customers.</p><p>Emerald Pathways will take the guesswork out of knowing what to post and when. We can create templates and style guides for all of the major social networks tailored to your Irish online business. We can schedule this original content to go live at peak times, ensuring your business gets the maximum engagement.</p><p>We also offer full social media training to give you the knowledge to promote and expand your business online.</p></section><QuoteCta />
  <section className="gallery-section"><GalleryHeading title="Social Media Video Posts">We record high quality video and design effective social media posts for our customers&apos; brands.</GalleryHeading><p className="video-enquiry">Our current video examples are available on request. <a href={`${import.meta.env.BASE_URL}contact/`}>Ask to see our video work</a>.</p></section>
  <section className="gallery-section"><GalleryHeading title="Social Media Photo Posts">We produce photographic content that represents our clients&apos; brands and speaks to their audiences.</GalleryHeading><div className="media-grid social-photo-grid"><img src={publicAsset("assets/social_picadice_photo.jpg")} alt="Picadice photographic social post" width={509} height={509} loading="lazy" /><img src={publicAsset("assets/social_tuath_photo.jpg")} alt="Túath Glass photographic social post" width={509} height={509} loading="lazy" /></div></section>
  <section className="gallery-section"><GalleryHeading title="Social Media Audits">We implement full social media audits before we start working on a project. We utilise the clients best attributes and create a workable timeline and schedule to increase engagement and maximise retention.</GalleryHeading><div className="media-grid social-audit-grid"><img src={publicAsset("assets/social_audit_map_full.jpg")} alt="Complete social audience map from an audit" width={1200} height={550} loading="lazy" /><img src={publicAsset("assets/social_audit_chart_full.jpg")} alt="Complete social media comparison chart from an audit" width={1200} height={550} loading="lazy" /></div></section>
  <section className="gallery-section"><GalleryHeading title="Logo Design">We have designed logos for our past clients which feature our signature aesthetic.</GalleryHeading><div className="media-grid social-logo-grid"><img src={publicAsset("assets/social_whiskey_experts_full.png")} alt="The Whiskey Experts complete logo" width={1080} height={1080} loading="lazy" /><img src={publicAsset("assets/social_whiskey_school_full.png")} alt="Whiskey School complete logo" width={1080} height={1080} loading="lazy" /></div></section></div>
</main></SiteShell>; }
